id: P006634
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12531
  title: འབྲུག་པ་བཀའ་བརྒྱུད་པའི་ཆོ་གའི་རྣམ་བཤད།
  author: ''
  volumes:
    4550653726f141298902f1c74bc8d8a8:
      image_group_id: I1KG12556
      title: ''
      volume_number: 1
      total_pages: 416
      base_file: v001.txt
